{
 "title": "GPUs",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(ospool_claimed_gpus_count{namespace=\"osg\"}) / sum(ospool_total_gpus_count{namespace=\"osg\"}) * 100 != 0",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Capability Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(capability) (ospool_total_gpus_capability{namespace=\"osg\"}) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Breakdown (GB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(memory) (ospool_total_gpus_memory{namespace=\"osg\"}) != 0",
     "legendFormat": "{{memory}} GB"
    }
   ]
  },
  {
   "title": "Claimed GPUs per Resource",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(resource_name) (ospool_claimed_gpus_count{namespace=\"osg\"}) != 0",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Idle GPUs per Resource",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(sum by(resource_name) (ospool_idle_gpus_count{namespace=\"osg\"})) != 0",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Claimed GPUs per Capability",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sort_desc(sum by(capability) (ospool_claimed_gpus_capability{namespace=\"osg\"})) != 0",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Idle GPUs per Capability",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sort_desc(sum by(capability) (ospool_idle_gpus_capability{namespace=\"osg\"})) != 0",
     "legendFormat": "{{resource_name}}"
    }
   ]
  }
 ]
}