{
 "title": "Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(ospool_claimed_cpus_count{namespace=\"osg\"})",
     "legendFormat": "Claimed"
    },
    {
     "expr": "sum(ospool_idle_retirement_cpus_count{namespace=\"osg\"})",
     "legendFormat": "Idle - Retirement"
    },
    {
     "expr": "sum(ospool_idle_memstarvation_cpus_count{namespace=\"osg\"})",
     "legendFormat": "Idle - Memory Starvation"
    },
    {
     "expr": "sum(ospool_idle_diskstarvation_cpus_count{namespace=\"osg\"})",
     "legendFormat": "Idle - Disk Starvation"
    },
    {
     "expr": "sum(ospool_idle_blackhole_cpus_count{namespace=\"osg\"})",
     "legendFormat": "Idle - Black Hole"
    },
    {
     "expr": "sum(ospool_idle_other_cpus_count{namespace=\"osg\"})",
     "legendFormat": "Idle - Other"
    }
   ]
  },
  {
   "title": "GPU States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(ospool_claimed_gpus_count{namespace=\"osg\"})",
     "legendFormat": "Claimed"
    },
    {
     "expr": "sum(ospool_idle_gpus_count{namespace=\"osg\"})",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Top Running Jobs per users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sort_desc(sum by(submitter) (ospool_submitter_running_jobs_count{namespace=\"osg\"})) > 200",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(ospool_submitter_idle_jobs_count{namespace=\"osg\"})",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Running/Held Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(ospool_submitter_running_jobs_count{namespace=\"osg\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(ospool_submitter_held_jobs_count{namespace=\"osg\"})",
     "legendFormat": "Held"
    }
   ]
  }
 ]
}