{
 "title": "Health",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Machine Ads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ospool_machine_ads{namespace=\"osg\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Black Holes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ospool_idle_blackhole_cpus_count{namespace=\"osg\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSDF",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ospool_osdf{namespace=\"osg\"}) / sum(ospool_machine_ads{namespace=\"osg\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CVMFS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ospool_cvmfs{namespace=\"osg\"}) / sum(ospool_machine_ads{namespace=\"osg\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apptainer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ospool_apptainer{namespace=\"osg\"}) / sum(ospool_machine_ads{namespace=\"osg\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apptainer SIF",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ospool_apptainer_sif{namespace=\"osg\"}) / sum(ospool_machine_ads{namespace=\"osg\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EP Outbound Firewalls",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ospool_firewall{namespace=\"osg\"}) / sum(ospool_machine_ads{namespace=\"osg\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Glidein Group",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by(glidein_group) (ospool_glidein_group{namespace=\"osg\"})",
     "legendFormat": "{{glidein_group}}"
    }
   ]
  },
  {
   "title": "Glidein Versions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by(glidein_version) (ospool_glidein_version{namespace=\"osg\"})",
     "legendFormat": "{{glidein_version}}"
    }
   ]
  },
  {
   "title": "Default OS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(default_os) (ospool_default_os{namespace=\"osg\"})",
     "legendFormat": "{{default_os}}"
    }
   ]
  },
  {
   "title": "Microarch",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by(microarch) (ospool_microarch{namespace=\"osg\"})",
     "legendFormat": "{{microarch}}"
    }
   ]
  },
  {
   "title": "Kernel Versions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(kernel_version) (ospool_kernel_versions{namespace=\"osg\"})",
     "legendFormat": "{{kernel_version}}"
    }
   ]
  },
  {
   "title": "Pelican Versions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(pelican_version) (ospool_pelican_versions{namespace=\"osg\"})",
     "legendFormat": "{{kernel_version}}"
    }
   ]
  }
 ]
}