{
 "title": "OSDF",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Endpoint",
    "query": "{\"find\":\"terms\",\"field\":\"Endpoint\"}"
   },
   {
    "name": "ScheddName",
    "label": "AP",
    "query": "{\"find\":\"terms\",\"field\":\"ScheddName\"}"
   },
   {
    "name": "TransferType",
    "query": "{\"find\":\"terms\",\"field\":\"TransferType\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "OSDF Successes (5 min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "RecordTime", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\" AND FinalAttempt:true AND TransferSuccess:true",
     "timeField": "RecordTime"
    }
   ]
  },
  {
   "title": "Bytes transferred per OSDF endpoint (cache/origin)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Endpoint",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "AttemptFileBytes", "id": "1", "type": "sum" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\"",
     "timeField": "RecordTime"
    }
   ]
  },
  {
   "title": "OSDF Failures (5 min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "Director",
     "bucketAggs": [
      { "field": "RecordTime", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ScheddName:$ScheddName AND TransferProtocol:\"osdf\" AND AND TransferType:$TransferType (FinalAttempt:false OR (FinalAttempt:true AND TransferSuccess:false)) AND NOT _exists_:Endpoint",
     "timeField": "RecordTime"
    },
    {
     "alias": "Cache/Origin",
     "bucketAggs": [
      {
       "id": "3",
       "settings": { "interval": "5m", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferProtocol:\"osdf\" AND (FinalAttempt:false OR (FinalAttempt:true AND TransferSuccess:false)) AND _exists_:Endpoint",
     "timeField": "RecordTime"
    }
   ]
  },
  {
   "title": "Transfer attempt failures per OSDF endpoint (cache/origin)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Endpoint",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\" AND (FinalAttempt:false OR (FinalAttempt:true AND TransferSuccess:false))",
     "timeField": "RecordTime"
    }
   ]
  },
  {
   "title": "Percent failed attempts per OSDF endpoint (cache/origin)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Endpoint",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "500" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\"",
     "timeField": "RecordTime"
    },
    {
     "bucketAggs": [
      {
       "field": "Endpoint",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "500" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\" AND (FinalAttempt:true AND TransferSuccess:true)  ",
     "timeField": "RecordTime"
    },
    {
     "bucketAggs": [
      {
       "field": "Endpoint",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "500" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\" AND (FinalAttempt:false OR (FinalAttempt:true AND TransferSuccess:false))",
     "timeField": "RecordTime"
    }
   ]
  },
  {
   "title": "Percent failed attempts per OSDF endpoint (cache/origin)",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Endpoint",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "500" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\"",
     "timeField": "RecordTime"
    },
    {
     "bucketAggs": [
      {
       "field": "Endpoint",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "500" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\" AND (FinalAttempt:true AND TransferSuccess:true)  ",
     "timeField": "RecordTime"
    },
    {
     "bucketAggs": [
      {
       "field": "Endpoint",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "500" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\" AND (FinalAttempt:false OR (FinalAttempt:true AND TransferSuccess:false))",
     "timeField": "RecordTime"
    }
   ]
  },
  {
   "title": "Transfer attempt failures per OSPool Site (where available)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "machineattrglidein_site0.indexed",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\" AND (FinalAttempt:false OR (FinalAttempt:true AND TransferSuccess:false)) AND _exists_:machineattrglidein_site0.indexed",
     "timeField": "RecordTime"
    }
   ]
  },
  {
   "title": "Percent failed attempts per OSPool Site",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "machineattrglidein_site0.indexed",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "500" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\" AND _exists_:machineattrglidein_site0.indexed",
     "timeField": "RecordTime"
    },
    {
     "bucketAggs": [
      {
       "field": "machineattrglidein_site0.indexed",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "500" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\" AND (FinalAttempt:true AND TransferSuccess:true) AND _exists_:machineattrglidein_site0.indexed",
     "timeField": "RecordTime"
    },
    {
     "bucketAggs": [
      {
       "field": "machineattrglidein_site0.indexed",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "500" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\" AND (FinalAttempt:false OR (FinalAttempt:true AND TransferSuccess:false)) AND _exists_:machineattrglidein_site0.indexed",
     "timeField": "RecordTime"
    }
   ]
  },
  {
   "title": "Percent failed attempts per OSPool Site",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "machineattrglidein_site0.indexed",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "500" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\" AND _exists_:machineattrglidein_site0.indexed",
     "timeField": "RecordTime"
    },
    {
     "bucketAggs": [
      {
       "field": "machineattrglidein_site0.indexed",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "500" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\" AND (FinalAttempt:true AND TransferSuccess:true) AND _exists_:machineattrglidein_site0.indexed",
     "timeField": "RecordTime"
    },
    {
     "bucketAggs": [
      {
       "field": "machineattrglidein_site0.indexed",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "500" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Endpoint:$Endpoint AND ScheddName:$ScheddName AND TransferType:$TransferType AND TransferProtocol:\"osdf\" AND (FinalAttempt:false OR (FinalAttempt:true AND TransferSuccess:false)) AND _exists_:machineattrglidein_site0.indexed",
     "timeField": "RecordTime"
    }
   ]
  }
 ]
}